name: Tegara
channels:
  - conda-forge
  - defaults
dependencies:
  - screeninfo
  - opencv
  - pytorch
  - numpy
  - torch
  - opencv-python
  - cvzone
  - mediapipe=0.10.9
  - ultralytics
  - lap
#python -m pip install paddlepaddle==3.2.2 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
#pip install paddleocr